%mean amp
ALLERP = pop_geterpvalues( '\\atlas-rstor01.ad.uillinois.edu\research\ELPLab\Experiments\Tone\EEG\GA\GMList_JK.txt', [ 300 600],...
 [ 3:2:9 10],  1:28 , 'Baseline', 'pre', 'Binlabel', 'on', 'FileFormat', 'wide', 'Filename', 'Mandarin_150-300.', 'Fracreplace', 'NaN',...
 'InterpFactor',  1, 'Measure', 'meanbl', 'Resolution',  3 );

%peak amp
ALLERP = pop_geterpvalues( '\\atlas-rstor01.ad.uillinois.edu\research\ELPLab\Experiments\Tone\EEG\GA\GMlist_JK.txt', [ 300 600],...
    [ 3:2:9 10], 1:28 , 'Baseline', 'pre', 'Binlabel', 'on', 'FileFormat', 'wide', 'Filename', 'Mandarin_300-600_peak_amplitude',...
 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peakampbl', 'Neighborhood',  3, 'Peakpolarity',...
 'positive', 'Peakreplace', 'absolute', 'Resolution',  3 );

%peak latency
ALLERP = pop_geterpvalues( '\\atlas-rstor01.ad.uillinois.edu\research\ELPLab\Experiments\Tone\EEG\GA\GMlist_JK.txt', [ 300 600], [ 3:2:9 10],...
  1:28 , 'Baseline', 'pre', 'Binlabel', 'on', 'FileFormat', 'wide', 'Filename', 'Mandarin_300-600_peak_latency',...
 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peaklatbl', 'Neighborhood',  3, 'Peakpolarity',...
 'positive', 'Peakreplace', 'absolute', 'Resolution',  3 );
